name: Fetch Keno API

on:
  schedule:
    # Chạy mỗi 5 phút, bạn có thể chỉnh theo nhu cầu
    - cron: '*/5 * * * *'
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  fetch-keno:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch Keno API
      run: |
        echo "Fetching Keno data..."
        curl -s "https://veso247.vn:19901/api/keno/result/keno?page_size=10&page_index=1" -o temp.json
        node <<'EOF'
        const fs = require('fs');
        const data = JSON.parse(fs.readFileSync('temp.json'));
        if(!data?.data?.items?.length) { console.log("No data"); process.exit(0); }

        const newResults = data.data.items.map(item => ({
          date: item.openDate.split(" ")[0],
          draw: "#" + item.drawCode,
          nums: Array.from({length:20},(_,i)=>Number(item["num"+(i+1)]))
        }));

        let existing = [];
        if(fs.existsSync('keno_data.json')){
          existing = JSON.parse(fs.readFileSync('keno_data.json'));
        }

        // Gộp, tránh trùng draw
        const merged = [...newResults, ...existing.filter(r => !newResults.some(n => n.draw === r.draw))];

        fs.writeFileSync('keno_data.json', JSON.stringify(merged, null, 2));
        EOF

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add keno_data.json
        git commit -m "Update keno_data.json from API" || echo "No changes to commit"
        git push
